"""Builds supabase/seed.sql from data/companies.json.

data/companies.json is the one place company and branch details are kept.
Edit it, run this, then run supabase/seed.sql in the Supabase SQL Editor.

    python tools/build_seed.py

Re-running the seed is safe: it updates existing companies and branches and
keeps each company's claim, status and reviews.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
companies = json.loads((ROOT / "data" / "companies.json").read_text(encoding="utf-8"))

COMPANY_COLUMNS = ["id", "kind", "name", "category", "description", "email", "website", "contact", "items", "extra",
                   "serves", "license", "founded", "image_url", "image_is_photo", "image_source", "checked_on"]
BRANCH_COLUMNS = ["id", "company_id", "sort_order", "name", "address", "lat", "lng", "approx_location", "phones",
                  "hours_text", "schedule", "always_open", "contact", "page"]


def sql(value):
    """A Python value as a SQL literal."""
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, dict):
        return sql(json.dumps(value)) + "::jsonb"
    if isinstance(value, list):
        return "array[" + ", ".join(sql(v) for v in value) + "]::text[]" if value else "'{}'::text[]"
    return "'" + str(value).replace("'", "''") + "'"


def upsert(table, columns, row):
    values = ", ".join(sql(row.get(c)) for c in columns)
    updates = ", ".join(f"{c} = excluded.{c}" for c in columns if c != "id")
    return f"insert into public.{table} ({', '.join(columns)}) values ({values})\n  on conflict (id) do update set {updates};"


def main():
    lines = [
        "-- Co-op seed data. Generated by tools/build_seed.py from data/companies.json. Don't edit by hand.",
        f"-- {len(companies)} companies, {sum(len(c['branches']) for c in companies)} branches.",
        "begin;",
    ]
    for c in companies:
        lines.append("")
        lines.append(f"-- {c['name']}")
        lines.append(upsert("companies", COMPANY_COLUMNS, c))
        ids = []
        for i, b in enumerate(c["branches"], start=1):
            row = {**b, "company_id": c["id"], "sort_order": i}
            ids.append(b["id"])
            lines.append(upsert("branches", BRANCH_COLUMNS, row))
        lines.append(f"delete from public.branches where company_id = {sql(c['id'])} and id <> all({sql(ids)});")
    lines.append("")
    lines.append("commit;")
    out = ROOT / "supabase" / "seed.sql"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out.relative_to(ROOT)}: {len(companies)} companies")


if __name__ == "__main__":
    main()
